"""
src/feedback_ingestion.py

Feedback ingestion — Gmail IMAP polling (Section 7.3)

Polls a dedicated Gmail mailbox for feedback replies to Stage 9 notification
emails, parses them, and appends records to data/logs/feedback.jsonl.

Expected reply structure (generated by the mailto links in Stage 9):
  Subject: [TRIPWIRE] Feedback — {run_id} — {page_id}
  Body:
    run_id: {run_id}
    page_id: {page_id}
    source_id: {source_id}
    category: {category}

    Additional comments (optional):
    {free text}

Parsing rules:
  • Only UNSEEN messages with "[TRIPWIRE]" in the subject are processed.
  • Fields are extracted from the structured body lines (key: value).
  • If mandatory fields (run_id, page_id, category) are missing, the message
    is left UNREAD and a warning is logged — it will be retried next cycle.
  • Successfully parsed messages are marked READ.
  • Each parsed record is appended to feedback.jsonl as a single JSON line.
  • The updated feedback.jsonl is committed and pushed to the repository
    (done by the workflow after this script exits).

Only Python standard library modules are used (imaplib, email, json, os, re).
"""

from __future__ import annotations

import email as email_lib
import email.header
import email.policy
import imaplib
import json
import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_IMAP_HOST = "imap.gmail.com"
_IMAP_PORT = 993
_SUBJECT_TAG = "[TRIPWIRE]"
_REQUIRED_FIELDS = {"run_id", "page_id", "category"}

_VALID_CATEGORIES = {
    "useful",
    "not_significant",
    "wrong_amendment",
    "wrong_page",
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def ingest_feedback(
    gmail_user: str | None = None,
    gmail_password: str | None = None,
    feedback_log_path: str | Path | None = None,
    dry_run: bool = False,
) -> list[dict[str, Any]]:
    """Poll Gmail for unread Tripwire feedback replies and append to feedback.jsonl.

    Parameters
    ----------
    gmail_user:
        Gmail address.  Defaults to the FEEDBACK_GMAIL_USER environment variable.
    gmail_password:
        Gmail App Password.  Defaults to FEEDBACK_GMAIL_APP_PASSWORD env var.
    feedback_log_path:
        Path to the feedback JSONL file.  Defaults to data/logs/feedback.jsonl
        relative to the repository root.
    dry_run:
        If True, parse and return records without writing to disk or marking
        messages as read.  Useful for testing.

    Returns
    -------
    list[dict]
        Parsed feedback records ingested in this call.
    """
    gmail_user = gmail_user or os.environ.get("FEEDBACK_GMAIL_USER", "")
    gmail_password = gmail_password or os.environ.get(
        "FEEDBACK_GMAIL_APP_PASSWORD", ""
    )

    if not gmail_user or not gmail_password:
        raise ValueError(
            "Gmail credentials not provided.  Set FEEDBACK_GMAIL_USER and "
            "FEEDBACK_GMAIL_APP_PASSWORD environment variables."
        )

    if feedback_log_path is None:
        repo_root = Path(__file__).parent.parent
        feedback_log_path = repo_root / "data" / "logs" / "feedback.jsonl"
    feedback_log_path = Path(feedback_log_path)

    logger.info("Connecting to Gmail IMAP as %s …", gmail_user)
    mail = imaplib.IMAP4_SSL(_IMAP_HOST, _IMAP_PORT)
    mail.login(gmail_user, gmail_password)
    mail.select("inbox")

    # Search for unread messages tagged with [TRIPWIRE].
    _, id_data = mail.search(None, f'UNSEEN SUBJECT "{_SUBJECT_TAG}"')
    message_ids = id_data[0].split() if id_data[0] else []
    logger.info("Found %d unread [TRIPWIRE] message(s).", len(message_ids))

    ingested: list[dict[str, Any]] = []
    failed_ids: list[bytes] = []

    for msg_id in message_ids:
        _, msg_data = mail.fetch(msg_id, "(RFC822)")
        if not msg_data or not msg_data[0]:
            logger.warning("Could not fetch message id=%s — skipping.", msg_id)
            continue

        raw_bytes = msg_data[0][1]
        if not isinstance(raw_bytes, bytes):
            logger.warning("Unexpected message format for id=%s — skipping.", msg_id)
            continue

        parsed_msg = email_lib.message_from_bytes(
            raw_bytes, policy=email_lib.policy.default
        )
        record = _parse_message(parsed_msg)

        if record is None:
            logger.warning(
                "Could not parse message id=%s (missing required fields) — "
                "leaving unread for retry.",
                msg_id,
            )
            failed_ids.append(msg_id)
            continue

        ingested.append(record)

        if not dry_run:
            # Mark as read.
            mail.store(msg_id, "+FLAGS", "\\Seen")

    mail.logout()

    if ingested and not dry_run:
        _append_records(feedback_log_path, ingested)
        logger.info(
            "Appended %d feedback record(s) to %s.", len(ingested), feedback_log_path
        )

    if failed_ids:
        logger.warning(
            "%d message(s) could not be parsed and were left unread: %s",
            len(failed_ids),
            [fid.decode() for fid in failed_ids],
        )

    return ingested


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _parse_message(msg: Any) -> dict[str, Any] | None:
    """Extract a feedback record from an email.Message object.

    Returns None if mandatory fields are absent or unparseable.
    """
    subject = _decode_header_value(msg.get("Subject", ""))
    date_str = msg.get("Date", "")
    ingested_at = datetime.now(timezone.utc).isoformat()

    body = _extract_body(msg)
    fields = _parse_structured_body(body)

    # Validate required fields.
    for required in _REQUIRED_FIELDS:
        if not fields.get(required):
            logger.debug(
                "Missing required field '%s' in message with subject: %r",
                required,
                subject,
            )
            return None

    # Normalise category.
    category = fields.get("category", "").strip().lower().replace(" ", "_")
    if category not in _VALID_CATEGORIES:
        logger.warning(
            "Unrecognised category %r — treating as malformed.", category
        )
        return None

    return {
        "run_id": fields["run_id"].strip(),
        "page_id": fields["page_id"].strip(),
        "source_id": fields.get("source_id", "").strip(),
        "category": category,
        "comment": fields.get("_comment", "").strip(),
        "email_subject": subject,
        "email_date": date_str,
        "ingested_at": ingested_at,
    }


def _extract_body(msg: Any) -> str:
    """Extract plain-text body from an email.Message object."""
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            if content_type == "text/plain":
                charset = part.get_content_charset() or "utf-8"
                payload = part.get_payload(decode=True)
                if isinstance(payload, bytes):
                    return payload.decode(charset, errors="replace")
        return ""
    else:
        charset = msg.get_content_charset() or "utf-8"
        payload = msg.get_payload(decode=True)
        if isinstance(payload, bytes):
            return payload.decode(charset, errors="replace")
        return str(payload or "")


def _parse_structured_body(body: str) -> dict[str, str]:
    """Parse the structured key: value lines from the email body.

    The body format produced by Stage 9's mailto links is:
      run_id: {value}
      page_id: {value}
      source_id: {value}
      category: {value}

      Additional comments (optional):
      {free text}

    Anything after the blank line following "Additional comments" is treated
    as the free-text comment.
    """
    fields: dict[str, str] = {}
    lines = body.splitlines()

    # Extract key: value pairs at the top of the body.
    structured_keys = {"run_id", "page_id", "source_id", "category"}
    structured_end = 0
    for i, line in enumerate(lines):
        match = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)", line)
        if match:
            key = match.group(1).lower()
            value = match.group(2).strip()
            if key in structured_keys:
                fields[key] = value
            structured_end = i + 1
        elif line.strip() == "" and i < len(lines) - 1:
            # End of structured section.
            structured_end = i + 1
            break

    # Everything after the structured header and optional "Additional comments"
    # marker is the free-text comment.
    comment_lines: list[str] = []
    in_comment = False
    for line in lines[structured_end:]:
        lower = line.strip().lower()
        if lower.startswith("additional comment"):
            in_comment = True
            continue
        if in_comment and line.strip():
            comment_lines.append(line)
        elif not in_comment and line.strip():
            # Unexpected content after structured section — include in comment.
            comment_lines.append(line)

    if comment_lines:
        fields["_comment"] = "\n".join(comment_lines)

    return fields


def _decode_header_value(header_value: str) -> str:
    """Decode a potentially RFC 2047-encoded email header value."""
    parts = email.header.decode_header(header_value)
    decoded_parts: list[str] = []
    for part, charset in parts:
        if isinstance(part, bytes):
            decoded_parts.append(
                part.decode(charset or "utf-8", errors="replace")
            )
        else:
            decoded_parts.append(str(part))
    return "".join(decoded_parts)


# ---------------------------------------------------------------------------
# JSONL persistence
# ---------------------------------------------------------------------------


def _append_records(path: Path, records: list[dict[str, Any]]) -> None:
    """Append records to the feedback JSONL file, creating it if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    parser = argparse.ArgumentParser(
        description="Ingest Tripwire feedback replies from Gmail."
    )
    parser.add_argument(
        "--feedback-log",
        default=None,
        help="Path to feedback.jsonl (default: data/logs/feedback.jsonl)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse messages without writing to disk or marking as read.",
    )
    args = parser.parse_args()

    records = ingest_feedback(
        feedback_log_path=args.feedback_log,
        dry_run=args.dry_run,
    )
    print(f"Ingested {len(records)} feedback record(s).")
    if args.dry_run:
        for r in records:
            print(json.dumps(r, indent=2))


if __name__ == "__main__":
    main()
